### PR TITLE
Ror4

### PR DESCRIPTION
**Pull request by raysuelzer**
Adding some new asset files started work on front page layout.

### CODE REVIEW

**Comment by JoeCohen** [comment]
Ray:
Thanks for all the work.  I will look at this after I get done dealing with the Failures caused by the merge from master.

**Comment by raysuelzer** [comment]
Great, I'm going to be traveling over the next few weeks, so I'm not sure
how much I will get done.

Ray Suelzer
Mobile: (312) 869-2665

**Comment by JoeCohen** [comment]
Ray:
Perhaps when you return, you could walk me through what needs to be done to replace the instances of `link_to_function` and `button_to_function` with ujs.  It's a black hole to me.

**Comment by raysuelzer** [comment]
The issue has been resolved in a pull request I made to master.  I'm not
sure what the merge status is.

Ray Suelzer
Mobile: (312) 869-2665

**Comment by raysuelzer** [comment]
re: pull requests -- I've been dragging my feet on PRs because I don't have
time to look at them closely.  But if you need me to do any merges, just
let me know and I'll just trust you and do them anyway.  Sorry!

-Jason

**Comment by JoeCohen** [comment]
Ray:
Thanks.  I completely forgot that I had asked you to do the pull requests
there.

Was it Pull Request 27
https://github.com/MushroomObserver/mushroom-observer/pull/27?

_--Joe Cohen_

**Comment by raysuelzer** [comment]
Yes.  That is it. You could also try and pull it from my javascript-updates
branch.

Ray Suelzer
Mobile: (312) 869-2665

**Comment by JoeCohen** [comment]
I will try to have a look later today or this evening.
If it's easy to resolve conflicts, I will pull it into the ror4-joe branch.

_--Joe Cohen_

**Comment by JoeCohen** [comment]
I pulled this to my local machine, merged, and pushed it back up to my repo. See aa67f18336c0372f7dd817cf3883b0b5c31d31b9

**Pull request closed without merging**
